from sqlmodel import Session, select
from database.datatables import Student, InfoFellow
from constants import FellowArea, FellowRank  # ajusta el import a tu proyecto


def seed_info_fellows(session: Session):
    
    existing = session.exec(select(InfoFellow)).first()

    if existing:
        return

    # Buscar IDs de students por studentCode
    def get_student_id(code: str) -> int:
        st = session.exec(select(Student).where(Student.studentCode == code)).first()
        if not st:
            raise ValueError(
                f"No existe student con studentCode={code}. Ejecuta seed_students primero."
            )
        return st.id

    fellows = [
        InfoFellow(
            fellow_code="L4F1C",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.PRE,
            isActive=True,
            idStudent=get_student_id("L4F1C"),
        ),
        InfoFellow(
            fellow_code="S23P12",
            area=FellowArea.GTH,
            fellow_rank=FellowRank.VI_PRE,
            isActive=True,
            idStudent=get_student_id("S23P12"),
        ),
        InfoFellow(
            fellow_code="M12G21",
            area=FellowArea.GTH,
            fellow_rank=FellowRank.DIRECTOR, 
            isActive=True, 
            idStudent=get_student_id("M12G21")
        ),
        InfoFellow(
            fellow_code="D10R20",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.DIRECTOR, 
            isActive=True, 
            idStudent=get_student_id("D10R20")
        ),
        InfoFellow(
            fellow_code="A9A", 
            area=FellowArea.MKT, 
            fellow_rank=FellowRank.DIRECTOR, 
            isActive=True, 
            idStudent=get_student_id("A9A")
        ),
        InfoFellow(
            fellow_code="M6D12C8C", 
            area=FellowArea.PMO, 
            fellow_rank=FellowRank.DIRECTOR, 
            isActive=True, 
            idStudent=get_student_id("M6D12C8C")
        ),
        InfoFellow(
            fellow_code="C1M5", 
            area=FellowArea.TI, 
            fellow_rank=FellowRank.DIRECTOR, 
            isActive=True, 
            idStudent=get_student_id("C1M5")
        ),
        InfoFellow(
            fellow_code="S5F19", 
            area=FellowArea.LKTYFNZ, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("S5F19")
        ),
        InfoFellow(
            fellow_code="Z1V27", 
            area=FellowArea.MKT, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("Z1V27")
        ),
        InfoFellow(
            fellow_code="I20V16", 
            area=FellowArea.PMO, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("I20V16")
        ),
        InfoFellow(
            fellow_code="A1S14", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("A1S14")
        ),
        InfoFellow(
            fellow_code="C12D20O", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("C12D20O")
        ),
        InfoFellow(
            fellow_code="E13R13", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("E13R13")
        ),
        InfoFellow(
            fellow_code="F14Z3", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("F14Z3")
        ),
        InfoFellow(
            fellow_code="J1B17", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("J1B17")
        ),
        InfoFellow(
            fellow_code="L5M1", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("L5M1")
        ),
        InfoFellow(
            fellow_code="V1V13", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("V1V13")
        ),
        InfoFellow(
            fellow_code="A14S1", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("A14S1")
        ),
        InfoFellow(
            fellow_code="A4U1", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=False, 
            idStudent=get_student_id("A4U1")
        ),
        InfoFellow(
            fellow_code="C13S4", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("C13S4")
        ),
        InfoFellow(
            fellow_code="J4A20", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("J4A20")
        ),
        InfoFellow(
            fellow_code="L1C19", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("L1C19")
        ),
        InfoFellow(
            fellow_code="M5F12", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("M5F12")
        ),
        InfoFellow(
            fellow_code="M10G7", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, idStudent=get_student_id("M10G7")
        ),
        InfoFellow(
            fellow_code="N14A21", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("N14A21")
        ),
        InfoFellow(
            fellow_code="R7C12", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("R7C12")
        ),
        InfoFellow(
            fellow_code="A13P3M", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("A13P3M")
        ),
        InfoFellow(
            fellow_code="D7C17", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("D7C17")
        ),
        InfoFellow(
            fellow_code="E9P2", 
            area=FellowArea.GTH, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("E9P2")
        ),
        InfoFellow(
            fellow_code="C9C3", 
            area=FellowArea.LKTYFNZ, 
            fellow_rank=FellowRank.MIEMBRO, 
            isActive=True, 
            idStudent=get_student_id("C9C3")
        ),
        InfoFellow(
            fellow_code="S19G",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("S19G"),
        ),
        InfoFellow(
            fellow_code="P10L20",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("P10L20"),
        ),
        InfoFellow(
            fellow_code="M5G23",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M5G23"),
        ),
        InfoFellow(
            fellow_code="M3T3",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M3T3"),
        ),
        InfoFellow(
            fellow_code="L1M12",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("L1M12"),
        ),
        InfoFellow(
            fellow_code="R1M1",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("R1M1"),
        ),
        InfoFellow(
            fellow_code="P3S3",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("P3S3"),
        ),
        InfoFellow(
            fellow_code="J10X23R",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J10X23R"),
        ),
        InfoFellow(
            fellow_code="E5D12C3",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("E5D12C3"),
        ),
        # PMO
        InfoFellow(
            fellow_code="M3H13",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M3H13"),
        ),
        InfoFellow(
            fellow_code="A11A19",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A11A19"),
        ),
        InfoFellow(
            fellow_code="J13E19",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J13E19"),
        ),
        InfoFellow(
            fellow_code="R4A21",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("R4A21"),
        ),
        InfoFellow(
            fellow_code="D1G23",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=False,
            idStudent=get_student_id("D1G23"),
        ),
        InfoFellow(
            fellow_code="D1M12",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("D1M12"),
        ),
        InfoFellow(
            fellow_code="D14AS",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("D14AS"),
        ),
        InfoFellow(
            fellow_code="A25L7",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A25L7"),
        ),
        InfoFellow(
            fellow_code="A13P3H",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A13P3H"),
        ),
        # PMO
        InfoFellow(
            fellow_code="D1S3",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("D1S3"),
        ),
        InfoFellow(
            fellow_code="S10V5",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("S10V5"),
        ),
        InfoFellow(
            fellow_code="R1Q3",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("R1Q3"),
        ),
        InfoFellow(
            fellow_code="A13I",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A13I"),
        ),
        # MKT
        InfoFellow(
            fellow_code="G21E4",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("G21E4"),
        ),
        InfoFellow(
            fellow_code="A1O13",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A1O13"),
        ),
        InfoFellow(
            fellow_code="S9G23",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("S9G23"),
        ),
        InfoFellow(
            fellow_code="M6C8",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M6C8"),
        ),
        InfoFellow(
            fellow_code="Y21G3",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("Y21G3"),
        ),
        InfoFellow(
            fellow_code="J4C19S",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J4C19S"),
        ),
        InfoFellow(
            fellow_code="J14H21",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J14H21"),
        ),
        InfoFellow(
            fellow_code="E26A23",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("E26A23"),
        ),
        InfoFellow(
            fellow_code="C23A19",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("C23A19"),
        ),
        # 30 LAST FELLOWS
        InfoFellow(
            fellow_code="D9G4L3",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("D9G4L3"),
        ),
        InfoFellow(
            fellow_code="D1G21",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=False,
            idStudent=get_student_id("D1G21"),
        ),
        InfoFellow(
            fellow_code="F2S17",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("F2S17"),
        ),
        InfoFellow(
            fellow_code="N1M21M",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("N1M21M"),
        ),
        InfoFellow(
            fellow_code="P3V4",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("P3V4"),
        ),
        InfoFellow(
            fellow_code="Y12R21",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("Y12R21"),
        ),
        InfoFellow(
            fellow_code="C19V3",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("C19V3"),
        ),
        InfoFellow(
            fellow_code="E1J23",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("E1J23"),
        ),
        InfoFellow(
            fellow_code="F14P3",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("F14P3"),
        ),
        InfoFellow(
            fellow_code="K13R20",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("K13R20"),
        ),
        InfoFellow(
            fellow_code="L1L5",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("L1L5"),
        ),
        InfoFellow(
            fellow_code="G1P3",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("G1P3"),
        ),
        InfoFellow(
            fellow_code="M6P12",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M6P12"),
        ),
        InfoFellow(
            fellow_code="M1G27",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M1G27"),
        ),
        InfoFellow(
            fellow_code="N19P4L3",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("N19P4L3"),
        ),
        InfoFellow(
            fellow_code="T26A17",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("T26A17"),
        ),
        InfoFellow(
            fellow_code="K7R1",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("K7R1"),
        ),
        InfoFellow(
            fellow_code="F13R19",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("F13R19"),
        ),
        InfoFellow(
            fellow_code="A7C16",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A7C16"),
        ),
        InfoFellow(
            fellow_code="A20C2",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A20C2"),
        ),
        InfoFellow(
            fellow_code="C10Q3",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("C10Q3"),
        ),
        InfoFellow(
            fellow_code="J10C21",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=False,
            idStudent=get_student_id("J10C21"),
        ),
        InfoFellow(
            fellow_code="L13P2",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("L13P2"),
        ),
        InfoFellow(
            fellow_code="M20H1",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M20H1"),
        ),
        InfoFellow(
            fellow_code="M4R13U",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M4R13U"),
        ),
        InfoFellow(
            fellow_code="M25D20",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M25D20"),
        ),
        InfoFellow(
            fellow_code="B13A5",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("B13A5"),
        ),
        InfoFellow(
            fellow_code="D10U3",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("D10U3"),
        ),
        InfoFellow(
            fellow_code="L1L3",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("L1L3"),
        ),
        InfoFellow(
            fellow_code="A21R21",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A21R21")
        ),
        InfoFellow(
            fellow_code="J1V3",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J1V3")
        ),
        InfoFellow(
            fellow_code="R1S3",
            area=FellowArea.GTH,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=False,
            idStudent=get_student_id("R1S3")
        ),
        InfoFellow(
            fellow_code="Z23R3",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=False,
            idStudent=get_student_id("Z23R3")
        ),
        InfoFellow(
            fellow_code="M17A",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=False,
            idStudent=get_student_id("M17A")
        ),
        InfoFellow(
            fellow_code="C3V13",
            area=FellowArea.GTH,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("C3V13")
        ),
        InfoFellow(
            fellow_code="J1SA",
            area=FellowArea.GTH,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J1SA")
        ),
        InfoFellow(
            fellow_code="J6P7",
            area=FellowArea.GTH,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J6P7")
        ),
        InfoFellow(
            fellow_code="Z1Z7",
            area=FellowArea.GTH,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("Z1Z7")
        ),
        InfoFellow(
            fellow_code="B14C2",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("B14C2")
        ),
        InfoFellow(
            fellow_code="B19L9",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("B19L9")
        ),
        InfoFellow(
            fellow_code="J6M13",
            area=FellowArea.LKTYFNZ,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J6M13")
        ),
        InfoFellow(
            fellow_code="F19R8",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("F19R8")
        ),
        InfoFellow(
            fellow_code="G19C5",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("G19C5")
        ),
        InfoFellow(
            fellow_code="K1G17",
            area=FellowArea.MKT,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("K1G17")
        ),
        InfoFellow(
            fellow_code="E4F6C",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("E4F6C")
        ),
        InfoFellow(
            fellow_code="M19V3",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M19V3")
        ),
        InfoFellow(
            fellow_code="O12F21",
            area=FellowArea.PMO,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("O12F21")
        ),
        InfoFellow(
            fellow_code="A12F8",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("A12F8")
        ),
        InfoFellow(
            fellow_code="E12I1",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("E12I1")
        ),
        InfoFellow(
            fellow_code="G19A3",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("G19A3")
        ),
        InfoFellow(
            fellow_code="J10A1",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("J10A1")
        ),
        InfoFellow(
            fellow_code="M13R1",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("M13R1")
        ),
        InfoFellow(
            fellow_code="O13E3",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("O13E3")
        ),
        InfoFellow(
            fellow_code="Y14C23",
            area=FellowArea.TI,
            fellow_rank=FellowRank.MIEMBRO,
            isActive=True,
            idStudent=get_student_id("Y14C23")
        ),
    ]
    session.add_all(fellows)
    session.commit()
    print("✅ Seeder ejecutado correctamente")
