from sqlmodel import Session, select
from database.datatables import  ProjectMember
from constants import Roles

def seed_member(session: Session):
 
    existing = session.exec(select(ProjectMember)).first()

    if existing:
        return
    
    projectmembers = [
        ProjectMember(
            project_id=1,
            member_id=72,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=92,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=78,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=1,
            member_id=66,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=64,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=74,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=79,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=1,
            member_id=48,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=43,
            rol=Roles.CRD
        ),
            ProjectMember(
            project_id=1,
            member_id=47,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=50,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=49,
            rol=Roles.DCT
        ),
        ProjectMember(
            project_id=1,
            member_id=39,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=36,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=1,
            member_id=31,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=37,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=13,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=23,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=1,
            member_id=19,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=21,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=22,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=18,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=61,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=90,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=1,
            member_id=91,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=56,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=58,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=82,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=89,
            rol=Roles.PTCP
        ),

        ProjectMember(
            project_id=2,
            member_id=11,
            rol=Roles.CRD
        ),  
        ProjectMember(
            project_id=2,
            member_id=27,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=15,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=28,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=24,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=25,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=26,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=63,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=2,
            member_id=73,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=68,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=62,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=71,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=70,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=77,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=57,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=2,
            member_id=9,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=53,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=84,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=85,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=88,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=83,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=87,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=44,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=2,
            member_id=10,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=51,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=40,
            rol=Roles.DCT
        ),
        ProjectMember(
            project_id=2,
            member_id=34,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=2,
            member_id=32,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=81,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=86,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=60,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=55,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=59,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=80,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=20,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=3,
            member_id=16,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=14,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=17,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=12,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=76,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=3,
            member_id=67,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=30,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=65,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=75,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=69,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=8,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=42,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=3,
            member_id=52,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=41,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=46,
            rol=Roles.DCT
        ),
        ProjectMember(
            project_id=3,
            member_id=33,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=3,
            member_id=38,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=35,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=90,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=88,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=60,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=58,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=9,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=89,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=84,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=4,
            member_id=87,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=77,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=8,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=70,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=78,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=71,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=64,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=66,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=4,
            member_id=24,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=16,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=26,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=17,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=14,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=12,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=51,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=10,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=52,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=4,
            member_id=47,
            rol=Roles.DCT
        ),
        ProjectMember(
            project_id=4,
            member_id=33,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=39,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=4,
            member_id=36,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=5,
            member_id=61,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=5,
            member_id=56,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=55,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=57,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=91,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=54,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=82,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=15,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=5,
            member_id=11,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=18,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=23,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=13,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=21,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=65,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=5,
            member_id=62,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=74,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=69,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=76,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=68,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=92,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=48,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=5,
            member_id=43,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=46,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=42,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=44,
            rol=Roles.DCT
        ),
        ProjectMember(
            project_id=5,
            member_id=35,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=5,
            member_id=37,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=5,
            member_id=38,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=80,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=6,
            member_id=53,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=86,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=81,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=59,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=85,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=73,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=6,
            member_id=30,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=63,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=72,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=79,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=67,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=20,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=6,
            member_id=28,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=19,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=29,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=22,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=25,
            rol=Roles.DCT
        ),
        ProjectMember(
            project_id=6,
            member_id=49,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=6,
            member_id=41,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=40,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=45,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=34,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=6,
            member_id=32,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=6,
            member_id=31,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=1,
            member_id=93,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=2,
            member_id=94,
            rol=Roles.PTCP
        ),
        ProjectMember(
            project_id=3,
            member_id=95,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=1,
            member_id=54,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=7,
            member_id=31,
            rol=Roles.CRD
        ),
        ProjectMember(
            project_id=7,
            member_id=61,
            rol=Roles.DCT
        ),

    ]
    session.add_all(projectmembers)
    session.commit()